version: '3'

services:
  jekyll:
    container_name: jekyll
    build:
      dockerfile: Dockerfile
      context: .
    command: jekyll serve --watch --force_polling --verbose -H 0.0.0.0 --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll